### ISSUE TITLE
Make variables white

### ISSUE THREAD

**Issue by LeonB** [ViViDboarder/wombat.nvim#1]
Hi! Thanks for the theme. I'm trying to extend the theme and make the variables white, just like in the original theme: https://github.com/sheerun/vim-wombat-scheme

Do you know how to accomplish that?

I'm currently trying this:

``` lua
local lush = require('lush')
local wombat = require('lush_theme.wombat_lush')
local c = require("lush_theme.wombat_lush_colors").colors

-- we can apply modifications ontop of the existing colorscheme
local spec = lush.extends({ wombat }).with(function()
    print(c.White)
    return {
        -- Use the existing Comment group in wombat, but adjust the gui attribute
        TSVariable { fg = c.White },
        Function { fg = c.White },
        TSVariableBuiltin = { fg = c.White },
    }
end)

-- then pass the extended spec to lush for application
lush(spec)
````

But it still show variables as green:

<img width="453" alt="Screenshot 2023-06-12 at 00 50 23" src="https://github.com/ViViDboarder/wombat.nvim/assets/3979/db558a1c-d64f-41e9-9be3-b0ec346898e4">

**Comment by LeonB** [comment]
Nevermind. 5 minutes after posting this I found the solution:

``` lua
            local lush = require('lush')
            local wombat = require('lush_theme.wombat_lush')
            local c = require("lush_theme.wombat_lush_colors").colors

            -- we can apply modifications ontop of the existing colorscheme
            local spec = lush.extends({ wombat }).with(function()
                return {
                    -- Use the existing Comment group in wombat, but adjust the gui attribute
                    Identifier { fg = c.White },
                }
            end)

            -- then pass the extended spec to lush for application
            lush.merge({ wombat, lush(spec) })

            -- enable colorscheme
            vim.cmd('colorscheme wombat_lush')
```

**Comment by ViViDboarder** [comment]
That’s cool! I based my theme on wombat256 rather than the version you shared, so these share the same inspiration. I’ll actually try this out and consider an alternative color for variables in `wombat_lush`.

**Comment by LeonB** [comment]
Ah, I see! After ten years or so of using the same vim config I updated to all the latest goodies which included TreeSitter. But I wanted to keep my favorite theme :)

I see some other little discrepancies (json keywords being purple for one). I'm going to try to keep a list and amend the colours.
